### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by stijnherreman** [JWMB/AzureAlerts2Slack#1]
It looks like the code has changed quite a bit since the README was written. Any chance you have some time to update it?

Also, thank you for creating this! I was about to do the same and then found your AzureMonitorCommonAlertSchemaTypes library, so this will save a lot of work :)

**Comment by JWMB** [comment]
Great to hear it's coming to some use despite being such a bare-bones project! Made a minor correction + added a link to how I actually use it in another repo.
